### ISSUE TITLE
Hard Freeze on Exiting Inventory

### ISSUE THREAD

**Issue by rsrogers4** [Lost-Outpost/septimus#325]
For what it is worth, I've had four hard freezes when trying to exit inventory screens in the few hours I've been playing beta-3. I have to use the task manager to terminate Skyrim. I think I saw this happen once in beta-2 and someone else mentioned they did as well.

Using the performance option, no other changes to beta-3

**Comment by Guitarninja2** [comment]
That's really strange :/ I haven't had it happen yet. If we can figure out how to make it happen I might be able to sort it out.

**Comment by rsrogers4** [comment]
It seems related to closing pop up dialogs when the inventory was open. Maybe some kind of race condition. If has happened twice when I opened a book from inventory to read it, and couldn’t close the book. And twice when I opened the lotd dwemer compass from inventory to set a waypoint, and closed it. Obviously it doesn’t happen every time.
________________________________

**Comment by micmou** [comment]
Now is it a hard freeze? No music cant bring up console etc?

**Comment by rsrogers4** [comment]
Good question. I was able to bring up the console. But I wasn’t able to exit out of inventory, move the character, or do anything else in game. Not sure about the music because I was playing with the sound off.
________________________________

**Comment by micmou** [comment]
not a hard freeze then
its that damn book problem again
hit r and youll get control back

**Comment by Guitarninja2** [comment]
Yeah it's more likely some sort of weird interaction happening rather than a hard crash or anything. I'll have to see what mods are messing with books.

**Comment by rsrogers4** [comment]
It also happened twice with the Dwemer compass menu, which isn’t a book.
________________________________

**Comment by Guitarninja2** [comment]
Hmmmmmmmm. Interesting heh. I wish I could make it happen consistently :/

**Comment by Xgatt** [comment]
Seems to happen more when you read quest-giving notes / books while sorting by unread first
