### ISSUE TITLE
Ring of Willpower is Overpower

### ISSUE THREAD

**Issue by Dog780** [Lost-Outpost/septimus#374]
The Ring of Willpower enchantment that says Spells are 25% stronger makes most things 25% stronger not just spells, a few examples I've found are Enchantments, items that are already enchanted enchantments, Shrines, Potions, and food. I think there is more but I'm not sure if listing more helps in any way.

**Comment by Xgatt** [comment]
Yeah, looks like it applies "Mod Spell Magnitude" without any conditions:
![Screenshot 2022-04-08 163938](https://user-images.githubusercontent.com/926013/162546967-d55df895-39df-4e4e-9e24-88af6e5eccac.png)

Compare this to something like the Auriel boost from Wintersun, which also boosts all spell maginitude when you get over 100 in a skill:
![Screenshot 2022-04-08 163846](https://user-images.githubusercontent.com/926013/162546995-bb27fa70-850f-4b8c-886f-33bdc3f52c2b.png)

This applies boosts per school of magic and adds the condition that the current spell has the school "Destruction", "Restoration", etc. I tried looking up how Thaumaturgy applies the boosts, and that's quite differently done. 

So an option that's fitting with this list can be to just pick the Thaumaturgy boosts to spell school magnitude and apply all 5 castable schools here.

I'll leave it to @Guitarninja2 to decide on this.
