### ISSUE TITLE
Dual-casting duration perks are inconsistent

### ISSUE THREAD

**Issue by desmok** [Lost-Outpost/septimus#417]
While having the illumination perk active within the restoration tree, the spells will sometimes double their duration and sometimes wont. This seems to apply to all of the spells that the perk affects, regeneration, rapid regeneration, attunement etc.

It seems to be a 50% chance either way from what I can tell.

**Comment by Xgatt** [comment]
The perk implementation seems correct to me. You're sure you are dual casting each time, and the same spell back to back shows inconsistent behavior?

**Comment by desmok** [comment]
Yea very sure. It is certainly strange, after playing through my save for a bit longer, I have noticed the dual cast perk in the alteration tree is also experiencing this behavior. 

A spell like ironflesh will sometime have a duration of 3 1/2 minutes, and sometimes 7. Haven't tested with the other alteration spells. 

I know at least, regeneration, rapid regeneration, mutagen and attunement all suffer from this issue. And I suspect the circle spells as well, but havn't confirmed.

I also tried to reset my stats with the reset potion to see if that would fix it but to no avail :(

**Comment by Durgenage** [comment]
This is happening to me too. It is very odd how inconsistent it is.

**Comment by Xgatt** [comment]
Can you test it with dual casting in general? Forget the resto spells and perks. Use any spell repeatedly and see if you get the dual casting bonus.

**Comment by desmok** [comment]
I did test out dual casting in general a tiny bit when I reset my character and I didn't notice anything off immediately, but I will have to double check when I am next home. Can't say for certain if dual casting itself is or isnt working correctly.

Just so I know, how long is dual casting suppose to increase duration by itself?

**Comment by Xgatt** [comment]
So dual casting restoration spells, by default, does not increase duration. It increases magnitude. I wanted to know if dual casting in general was not giving any bonuses, based on your comment about Ironflesh. Alteration spells DO increase in duration when Dual Cast.
