### ISSUE TITLE
Moon and Star "Misc Quest: One Dog Ain't Enough" mesh Bug

### ISSUE THREAD

**Issue by Xeohul** [Lost-Outpost/septimus#463]
Hallo,

it seems that one of the stuffed dogs you need to find at Darrosas house is under the wood pile and unobtainable without noclip.
I searched like 20 min for that last damn dog :(.

**Comment by luisnunessec** [comment]
Same thing happened to me, but by luck i spammed the x button and i got it in the middle of the bushes next to the wood pile
