### ISSUE TITLE
Artifacts descriptions wrong, potentially?

### ISSUE THREAD

**Issue by Dooshken** [Lost-Outpost/septimus#468]
At least some of the artifacts I've encountered (so far) that are altered by Antiquary seem to be bugged or wrong in some way. Based off of that mod page, the Gauldur Amulet is meant to offer 50 to each stat, in addition to 50% regen for each. The 50 to each stat seems to be active, despite the item's description in the armor menu, but unless the 50% regen to each is hidden, it seems to not be there. 

I can't tell exactly what's going on with the Mace of Molag Bal, but the item description in-game clearly doesn't look right. I used it very briefly and it didn't seem to be recharging itself with killing blows, like the Antiquary item description says it's meant to be doing.

Now that I'm looking around for more, I got this staff a while ago, and it's just straight up not doing what it says it's meant to be doing based off of the Antiquary mod page. I'm pretty sure it's just the Vanilla effect.

![Screenshot 2022-04-27 103923](https://user-images.githubusercontent.com/104334136/165557855-59155d31-ca47-4ecf-8634-281a47fcbc94.png)
![Screenshot 2022-04-27 103927](https://user-images.githubusercontent.com/104334136/165557877-3146960a-1592-439d-ba43-66a5ee932ac5.png)
![Screenshot 2022-04-27 103915](https://user-images.githubusercontent.com/104334136/165557833-32f95faf-5971-44b0-adf8-44c1b5018402.png)
![Screenshot 2022-04-27 104951](https://user-images.githubusercontent.com/104334136/165559397-6cce275a-0b5b-4522-adf6-4c8862829854.png)

**Comment by Guitarninja2** [comment]
I'm looking into it for 3.1. It should be resolved now in theory.
