### ISSUE TITLE
Equip Enchantment Fix Needs Critical Update

### ISSUE THREAD

**Issue by tohuw** [Lost-Outpost/septimus#490]
Version 1.3.5 fixes a critical bug which caused NPC enchants to duplicate. From the mod's changelog:

> Version 1.3.5
> Fixed an issue that caused effect duplication on NPCs in some situations if RedirectDispelWornItemEnchantsVisitor was enabled (introduced in 1.3.4)

This bug can be reproduced in the current version of Septimus.

**Comment by Guitarninja2** [comment]
Thank you. I included this update in 3.1
