### ISSUE TITLE
Enchantment | Can't learn Restoration's 'master robe', but can Destruction's & Alteration's

### ISSUE THREAD

**Issue by TuskLove** [Lost-Outpost/septimus#491]
-25% restoration spells cost & +50% magic regeneration -- restoration magic robe.

This restoration master robe doesn't even display at Enchanting table. Some other lower robes ot this school of magic also.
But destruction master robe and alteration _(-25% destruction/alteration spells cost & +50% magic regeneration)_ were displayed and learnt successfully. Novice robe was displayed and could be learnt _(screenshot)_
Don't know what is wrong _exactly_ - either restoration should be displayed and learnt like others, or others should not be able to be learnt in first place.

![enb2022_5_21_21_30_10](https://user-images.githubusercontent.com/105989953/169665064-c199f49d-40b8-4de6-a322-e30a439e92ff.jpg)
![enb2022_5_21_21_30_46](https://user-images.githubusercontent.com/105989953/169665065-4bfe1d28-3fd2-4cdb-acac-9a8dd7a8e9ad.jpg)
![enb2022_5_21_21_30_51](https://user-images.githubusercontent.com/105989953/169665066-d8f7e7a7-d745-4d55-96b4-3affeb9717e4.jpg)
![enb2022_5_21_21_31_19](https://user-images.githubusercontent.com/105989953/169665067-5aa0c47b-54d9-43e1-b012-ecb8c25c2046.jpg)

**Comment by Xgatt** [comment]
likely an issue with the disenchantable flag on these. will take a look

**Comment by Guitarninja2** [comment]
In theory it's fixed in 3.1.
