### ISSUE TITLE
Change in the readme

### ISSUE THREAD

**Issue by annakins** [Lost-Outpost/septimus#494]
Hi! I installed Septimus again. Looks like you still mention Animonculory here, so just putting that out there. :)

Support is offered in [The Lost Outpost](https://discord.gg/WF66mMu) server and in the [Issues](https://github.com/Guitarninja2/septimus/issues) section of the Septimus GitHub. If you have any questions following the add-on's instructions or if you find a typo or any other mistake in the documentation, feel free to report in _The Animonculory Discord server's support channel._

Cheers. ❤️

**Comment by Guitarninja2** [comment]
Nice lol. I definitely did a find and replace and apparently missed some spots hah. Thanks!
