### ISSUE TITLE
Animated Armory Silver whips perk issue and fix

### ISSUE THREAD

**Issue by Lukko-Dai** [Lost-Outpost/septimus#502]
The silver whips from the New Armory/Animated Armory mod have a keyword error causing the undead weapon damage bonus to not activate even though the correct script is attached to them. This includes the SilverWhipsDW entry as well.

WeapMaterialSteel needs to be updated to WeapMaterialSilver as shown below

edit: I did check through the other weapons (pike/q.staff/rapier/katana) and they all have the correct entry.

![unknown](https://user-images.githubusercontent.com/24244229/171221968-e7ca67f2-1141-47ed-94e9-37eb1a8ae9f3.png)

**Comment by Guitarninja2** [comment]
No longer using the whips in AA
