### ISSUE TITLE
High Elf weirdly shaped mouth area in character creation

### ISSUE THREAD

**Issue by Cinderskull** [Lost-Outpost/septimus#503]
I just tried creating my High Elf player character and everything is looking good, except for the mouth/jaw/chin area. It's not smooth at all and it looks this way for every single preset and every single mouth looks kinda off. It might be just some conflict between different mods or things not loading properly, but I don't know how to fix it exactly. I just installed the modlist via Wabbajack and did every other setup according to the ReadMe.
![weird](https://user-images.githubusercontent.com/106628795/171282965-c02e4c73-65fc-4552-b225-5fdee97171ee.png)

**Comment by Guitarninja2** [comment]
This is likely just from using a preset that's outdated. I can't really fix on my end unfortunately.
