### ISSUE TITLE
Cyrus' Saber replica spawned in world instead of normal. Bug only in AE version of Septimus.

### ISSUE THREAD

**Issue by lorywindrunner** [Lost-Outpost/septimus#508]
Located at "Wreck of the Brinehammer" Cyrus' Saber can be found stuck in the wall below deck, when playing the profile without CC content the correct version is spawned but when playing with AE content instead a replica spawns. Also note the model is different as there are some changes between CC and LOTD that aren't being applied consistently.

![20220605124724_1](https://user-images.githubusercontent.com/17264658/172068852-ba3f2eba-7256-4570-a318-501c19e856f7.jpg)
![20220605130124_1](https://user-images.githubusercontent.com/17264658/172068855-9555bf78-affa-43f8-a015-407092a55207.jpg)

**Comment by Scarlet-Stinger** [comment]
Intended behavior per the [LOTD Wiki](https://legacy-of-the-dragonborn.fandom.com/wiki/Cyrus%27_Saber). Quote:
"If the [Dead Man's Dread](http://en.uesp.net/wiki/Skyrim:Dead_Man's_Dread) creation and its [Creation Club Patch Hub](http://www.nexusmods.com/skyrimspecialedition/mods/31563) patch is installed, the [CC version](https://legacy-of-the-dragonborn.fandom.com/wiki/Cyrus%27_Sabre) of the weapon becomes the "default" and Auryen's quest is adjusted accordingly. **The version on the Brinehammer is replaced by the replica, using the CC model.**"

**Comment by Guitarninja2** [comment]
Thanks. I figured this was the case.
