### ISSUE TITLE
Armor pieces stored on horses disappear

### ISSUE THREAD

**Issue by Seag75** [Lost-Outpost/septimus#512]
Armor pieces stored in horses' inventories seem to disappear. This seems to (but it's not confirmed) to be linked to the summon function from Simplest Horses. 

Here is an example of an inventory where all armor items, except the Steel Shield and the Vagrant Hood disappeared:
![image1](https://user-images.githubusercontent.com/106589794/172470752-041a374c-4571-4f8a-bb52-ccea5254cc95.png) 

The circlets were removed from the inventory by me prior to the disappearance so they shouldn't be considered as "lost". When emptying the horse's inventory and performing the showInventory command after the disappearance of the items, the console looks like this :
![image2](https://user-images.githubusercontent.com/106589794/172471201-0c8074ff-fab0-4d67-8bc5-44c005443a26.png). 

This has been happening when using the horse purchased at Solitude stables.

Looking through the mod page and xEdit, it seemed this issue was connected to the "Respawn" and "UseInventory" flags in the horse records. Simplest Horses sets them as blank, while Simple Horse Tweaks sets them back to their vanilla value and overwrites it. (Post by user Urbon on [page 3](https://www.nexusmods.com/skyrimspecialedition/mods/54225?tab=posts&BH=2))

That said, according to another user on the mod page (Cornathan on [page 1](https://www.nexusmods.com/skyrimspecialedition/mods/54225?tab=posts&BH=2)) this doesn't have to do with the flags mentioned above (as he has them set correctly) but rather with the summon command itself, as when he summons them via console the armor does not disappear from the horse's inventory. Thus, this might be a deeper rooted - and less easily fixable - problem.

Nevertheless, I've forwarded the aforementioned flags from Simplest Horses in my patch that I'd made for Issue #501, and will update you on whether this problem persists (although I suspect it might).

**Comment by Guitarninja2** [comment]
Thank you for looking into this. I appreciate it!

**Comment by Seag75** [comment]
No worries! Thanks for the great list.

Just wanted to let you know that it seems the bug [has been fixed as per the latest update of Simplest Horses after the author was made aware of it.](https://www.nexusmods.com/skyrimspecialedition/mods/54225?tab=logs&BH=3).
