### ISSUE TITLE
Screen Resolution error

### ISSUE THREAD

**Issue by fancoir** [Lost-Outpost/septimus#516]
Just installed Septimus but on start-up I can only see the top left quarter of the screen. 

I'm using a 4K monitor and running a few instances of Skyrim - this is the only one with this problem.

**Comment by CasualAutopsy** [comment]
This is most likely the issue, some games tend to do this if this is set above 100%
make sure it isn't higher than 100%
![Screenshot 2022-06-18 195224](https://user-images.githubusercontent.com/107777585/174460487-dbe9f698-1ee2-4e44-9fda-1cc7fea77bcd.png)
