### ISSUE TITLE
Crash in Falkreath 

### ISSUE THREAD

**Issue by OniBlade1** [Lost-Outpost/septimus#521]
I wanted to do the miscellaneous quests to be thane of Falkreath. To be specific I have done Runil's hall of the dead quest, Thadgeir's quest and Zaria's quest. When I fast travel back to Falkreath after Zaria's quest the game crashes. I then thought hmm maybe its just a fast travel bug, I then went somewhere near by and the fps kept dropping like it was a slide show.

Falkreath on map: https://imgur.com/yeAeMUb

Falkreath taking shortcut to go to Falkreath fps drop: https://imgur.com/I8chWWq

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
