### ISSUE TITLE
Too many runes allowed

### ISSUE THREAD

**Issue by rsrogers4** [Lost-Outpost/septimus#522]
With the Rune Mage skill, I am able to place a seemingly unlimited number of frost runes (apprentice 'Frost Rune' spell).  I have not tested with other rune types. I have rule 11'd JS Ioun Stones, Better Third Person Selection (BTPS), and Skyshards. This happened before I installed BTPS.

**Comment by Guitarninja2** [comment]
I believe this is a known issue with adamant that might be fixed in the newest update.

**Comment by Guitarninja2** [comment]
Should be fixed in 3.2
