### ISSUE TITLE
Better SkyUI Config doesn't properly sort with Dark Mode UI enabled. 

### ISSUE THREAD

**Issue by Samitian** [Lost-Outpost/septimus#536]
Moving the mod below Dark Mode UI in MO2 seems to fix it. 
Sorting with mod in normal spot in the list:
![inventory](https://user-images.githubusercontent.com/13614924/175837386-bb870e28-1fa7-4d77-b21e-0d6df6558d01.png)
Sorting with mod moved to below Dark Mode UI:
![inventory2](https://user-images.githubusercontent.com/13614924/175837392-f2764992-7b93-49a6-8ce4-1a749e565372.png)

**Comment by Guitarninja2** [comment]
Fixed in 3.2
