### ISSUE TITLE
Ysgramor's Cloak uses same slot as Scarves, can be equipped alongside other cloaks. 

### ISSUE THREAD

**Issue by Samitian** [Lost-Outpost/septimus#543]
![Screenshot (2210)](https://user-images.githubusercontent.com/13614924/177003363-7da01740-c85d-456b-a0fa-1fe0942237b2.png)
![Screenshot (2211)](https://user-images.githubusercontent.com/13614924/177003369-40721817-52a3-4e19-9ca2-d47c3d145fbc.png)

**Comment by Webmetz** [comment]
Fixed in upcoming balancing patch
