### ISSUE TITLE
Silver weapons craftable without Silversmith perk.

### ISSUE THREAD

**Issue by Shurlikan** [Lost-Outpost/septimus#544]
![The Elder Scrolls V Skyrim Special Edition_2022 07 03-18 00_1](https://user-images.githubusercontent.com/19482151/177047715-aca4642c-d27a-4ccd-90e7-76648a882fa1.png)
![The Elder Scrolls V Skyrim Special Edition_2022 07 03-18 00](https://user-images.githubusercontent.com/19482151/177047717-d88d1cda-74d7-4a79-9afd-6f1e539495dc.png)

It is possible craft silver weapons without the Silversmith perk.
Septimus version: 3.1.1.1

**Comment by lawremi** [comment]
Just a note that these weapons come from the Animated Heavy Armoury mod: https://www.nexusmods.com/skyrimspecialedition/mods/35978

**Comment by Webmetz** [comment]
They came from Heavy Armory.  Fixed in 1.0.2 of https://www.nexusmods.com/skyrimspecialedition/mods/68342
