### ISSUE TITLE
Ultrawide dialogue too large

### ISSUE THREAD

**Issue by knaackville** [Lost-Outpost/septimus#547]
Hello.  It seems like the default dialogue is too large on ultrawide monitors, even with the widescreen fix, with part of the dialogue being cut off at the bottom.  

The dialoguemenu.swf is hidden in the Complete Widescreen Fix mod (.mohidden extension).  Unhiding it seems to fix the issue from what I can tell.

**Comment by Guitarninja2** [comment]
Thanks yeah. I'll fix that in 3.2
