### ISSUE TITLE
Growable Plants' Harrada Root Crash

### ISSUE THREAD

**Issue by Wibble199** [Lost-Outpost/septimus#548]
Harrada Root from [Skyrim Anniversary - Growable Plants](https://www.nexusmods.com/skyrimspecialedition/mods/58880) seems to be broken and causes a crash if the player plants it. The mod author was made aware in February but has not yet released a fix.

GuitarNinja suggested disabling that particular plant so no one else encounters this.

**Comment by Webmetz** [comment]
Sent Ninja a patch to fix it
