### ISSUE TITLE
Two-Handed Idle Clipping

### ISSUE THREAD

**Issue by Raketenpanzerbuchse** [Lost-Outpost/septimus#554]
The Two-Handed High Stance mod included in the list causes the left arm to look dislocated and clip into the torso. Looking at its modpage, it seems that this is a common issue. There's a "fix" but it presumes that you have CGO or MBO which this list doesn't use

![20220711_174331](https://user-images.githubusercontent.com/90899537/178295617-f0a0dd21-fa53-4400-b3f9-861d30efca49.jpg)

Since this list uses none of those mods, I used Notepad++ to look for any mention of that particular string and found a few that were set to a value other than zero but ultimately I didn't touch them. Here's how it looks in-game:

![20220711035515_1](https://user-images.githubusercontent.com/90899537/178296220-29b77808-6416-4118-ab1f-cd509fc69a5c.jpg)
![meyDS9N](https://user-images.githubusercontent.com/90899537/178296615-313d9632-0794-4067-918e-0ef782ddbea5.png)

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
