### ISSUE TITLE
Skyrim:Thane of Whiterun Quest bug

### ISSUE THREAD

**Issue by spenz91** [Lost-Outpost/septimus#559]
ID:	Favor253

Can't Progress to buy a house in whiterun.

![image](https://user-images.githubusercontent.com/109440431/179372977-4e211e50-3d2b-455c-bbb1-374978a3fd0d.png)

10		
Objective 10: Purchase a house in Whiterun

Can't get to Stage 20		
Objective 15: Return to <Alias.ShortName=QuestGiver>

Purchase Breezehome.
Return to the jarl for your reward.

**Comment by romkansk** [comment]
As found on discird the workaround is a console command: `setstage housepurchase 10`
