### ISSUE TITLE
A boss from Helgen Reborn is missing a knife texture

### ISSUE THREAD

**Issue by derekgits** [Lost-Outpost/septimus#562]
I used Soul Tear and made him my minion, that's why he's just standing there
![dre](https://user-images.githubusercontent.com/88917397/182050310-be58d911-0f90-492d-bb76-fa932fb34bb6.png)
![dre2](https://user-images.githubusercontent.com/88917397/182050311-c2061d05-8183-450a-8b04-4f7e30f119a1.png)

**Comment by derekgits** [comment]
i did install enb light and it effects some daedra weapons and that may be conflicting but not sure

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
