### ISSUE TITLE
Unable to use crafting tables

### ISSUE THREAD

**Issue by JuniMonster** [Lost-Outpost/septimus#563]
I installed the list yesterday, and my character is currently level 7 (and I’m having a great time!). Earlier in the game I was able to consistently use potions and enchanting stations (at the College of Winterhold). 

However, when I arrived at the Blue Palace and tried to use the palace’s enchanting table, I wasn’t able to use it. I was able to activate it, and the camera shifted into third person, but then my character just stood there for a few seconds. Then the camera shifted back to third person again. 

When I went across the room to use the potions table, I was able to use it successfully. 

I just got the museum opened up, and when I tried to use the main office’s table for making reproductions, I had the same experience as with the enchanting table. 

I’ve tried saving and reloading, fast traveling away and back, and quitting to desktop and reopening the game, but none of those have made the tables work. 

I just returned to the Blue Palace, and now I can’t use the potions table either. 

I have been able to use other enchanting and potions stations, so it seems to be tied to particular tables.  

Fingers crossed for a simple fix.

**Comment by freek925** [comment]
I've encountered the same issue a load of times. I solved it by going into third person and taking out my weapons. Apparently we get stuck in some animation which one it is I don't know.

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
