### ISSUE TITLE
Can’t switch to third person

### ISSUE THREAD

**Issue by JuniMonster** [Lost-Outpost/septimus#564]
I’m playing with a controller. I haven’t changed any settings, so switching to third person is mapped to pushing down the right stick. However, when I push down to switch pov, nothing happens. 

I play in first person, and I didn’t try switching pov until I was (unsuccessfully) trying to use an enchanting table, so I don’t know if it’s been like that since the beginning of the save game or if it’s a new problem. 

(I installed the list yesterday and am at level 7 with my first character. I reported the enchanting table issue separately)

**Comment by testnumber9000** [comment]
I just finished installing the Modlist and had the same issue. Camera switching works perfectly fine with mouse ant keyboard.
So i "manually" configured the controller setting in steam.


![fh](https://user-images.githubusercontent.com/99956415/185905585-ce58a1cf-dbdf-4660-b0b6-8859a8f8c1f7.jpg)
![2](https://user-images.githubusercontent.com/99956415/185905608-c3071c6f-6496-46cd-b8b5-79eaa7892c0c.jpg)
![4](https://user-images.githubusercontent.com/99956415/185905623-34697dd2-acf1-44f0-8e66-f21bed47ae9d.jpg)
![3](https://user-images.githubusercontent.com/99956415/185905629-e5e31cd1-7828-4319-9654-2fc360102a83.jpg)

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
