### ISSUE TITLE
The Eternal Chillrend Sound Bug

### ISSUE THREAD

**Issue by JeanJacquesJohnson** [Lost-Outpost/septimus#565]
Hello, 
Ive been playing for 200h with Septimus, and Ive finally encountered a real problem, which is not even related to the modlist but was reported all the back from the OG game in 2011.....

The lingering frost sound of Chillrend that you cant erase. Tried saving/reloading/restarting computer, then the usual changesex with console (temporary fix, since it will reappear at the next loading screen) 

Tying to go back to an early save is like restarting from the beginning, because it was so discreet I didnt pay much attention to it... And now that Ive finally acknowledged it as a bug Im only hearing it. 

So apparently the only way to get rid of it would be with mods, but i dont want to mess with the setup. 
So My question is do you think this one (for example) https://www.nexusmods.com/skyrimspecialedition/mods/5386
could be added to the list without destroying anything on my saves?

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
