### ISSUE TITLE
Physics bug from Artesian Cloaks of Skyrim

### ISSUE THREAD

**Issue by CorpCord** [Lost-Outpost/septimus#567]
There is a bug, apparently from Artesian Cloaks of Skyrim, where cloaks on dead bodies float off the ground and jerk around.
![unknown - 2022-09-08T162721 491](https://user-images.githubusercontent.com/113143624/189229020-2740d4b0-8919-4a43-a092-b6d7d668d064.png)

Other users report the bug on Artesian Cloaks of Skyrim's page on Nexus, and the bug goes away in Septimus when Artesian Cloaks of Skyrim is disabled.

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
