### ISSUE TITLE
Shields/weapons stuck after blocking (Septimus - Nemesis Output)

### ISSUE THREAD

**Issue by CorpCord** [Lost-Outpost/septimus#568]
When you block an attack with a shield or weapon and don't immediately counter-attack, your shield or weapon will stay in the blocking position. It can be lowered by pressing the block button again. This is caused by meshes\actors\character_1stperson\behaviors\1hm_behavior.hkx in Septimus - Nemesis Output.

**Comment by Guitarninja2** [comment]
Closed for Septimus 4.0.0
