### ISSUE TITLE
First issue WHOOP WHOOP jk just Moon and Star Stuff

### ISSUE THREAD

**Issue by Foamimi** [Lost-Outpost/septimus#571]
Helloooo, just wanted to see if these needed to be added back in (included the USSEP dock/books/landscape fixes just in case):

[Better Lighting for Moon and Star - with Lanterns of Skyrim II Patch](https://www.nexusmods.com/skyrimspecialedition/mods/43702)
[Moon and Star - Cleaned Plugin Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/28530)
[Moon and Star (MAS) - USSEP Dock Fix](https://www.nexusmods.com/skyrimspecialedition/mods/27419)
[Moon and Star (MAS) Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/27434)

bonus stuff since I'm getting ahead of myself (OOF SORRY)
[Landscape and Water Fixes - Moon and Star](https://www.nexusmods.com/skyrimspecialedition/mods/74512)
[Landscape Fixes For Grass Mods (Moon and Star + Helgen Reborn patches)](https://www.nexusmods.com/skyrimspecialedition/mods/9005)
[Moon and Star - Creation Club Consistency and Immersion Tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/67984) (alternative or in addition to Better Lighting for Moon and Star's Dragonborn Integration Patch)

ALSO remember to make Arissa's hair unplayable as it has purple hair textures

**Comment by Guitarninja2** [comment]
Thank you!!

**Comment by Guitarninja2** [comment]
Done :)
