### ISSUE TITLE
floor disappeared Hall of Counbtenance

### ISSUE THREAD

**Issue by Tukker4Always** [Lost-Outpost/septimus#581]
![Screenshot 2022-10-10 160251](https://user-images.githubusercontent.com/91663204/194884209-a168765b-a483-43dc-97fe-2f3634c3165c.png)

floor next to stairs going to level 2 in hall of countenance disappeared

**Comment by Tukker4Always** [comment]
Same goes for hall of attainment

**Comment by Guitarninja2** [comment]
Not seeing this issue.
