### ISSUE TITLE
Rock from Enhanced Landscapes Interfering with Moon and Star Docks

### ISSUE THREAD

**Issue by Foamimi** [Lost-Outpost/septimus#586]
Hello !! Just a couple of tiny hiccups I noticed while roaming about.

rock clipping:
[https://i.imgur.com/t1ZCT5U.png](https://i.imgur.com/t1ZCT5U.png)
[https://i.imgur.com/2jX98gJ.png](https://i.imgur.com/2jX98gJ.png)
[https://i.imgur.com/DsBTNB8.png](https://i.imgur.com/DsBTNB8.png)

then floating dungeon backside from Undeath:
[https://i.imgur.com/9a7k7Z0.png](https://i.imgur.com/9a7k7Z0.png)
[https://i.imgur.com/Gj723ky.png](https://i.imgur.com/Gj723ky.png)
[https://i.imgur.com/HRts7Cl.png](https://i.imgur.com/HRts7Cl.png)
[https://i.imgur.com/d7e6bKA.png](https://i.imgur.com/d7e6bKA.png)
[https://i.imgur.com/E9VdGOU.png](https://i.imgur.com/E9VdGOU.png)

ALSO may need that one mod (whose name I am forgetting off the top of my head) that resizes the MCM menu:
(ignore the Custom Light MCM, just using that for screenshots as it works kinda like FaceLight)
[https://i.imgur.com/I31vhD1.png](https://i.imgur.com/I31vhD1.png)

PS - the patch from Landscape Fixes for Grass Mods for Moon and Star is really great in execution, and helps stop the grass clipping through the chairs and fire pits. I know I know, I keep bringing it up, but it works! and you are a rebel for resisting grrrrr >:I

**Comment by Guitarninja2** [comment]
Fixed :)
