### ISSUE TITLE
Sadrith Kregan

### ISSUE THREAD

**Issue by FluffyCoyote** [Lost-Outpost/septimus#588]
![wut this](https://user-images.githubusercontent.com/115422756/194973587-ab18503d-c760-4495-8899-6f6237b8f0e2.PNG)
![wut this console](https://user-images.githubusercontent.com/115422756/194973594-40b968e6-08a3-4a4c-bd3a-ce2bee2355dc.PNG)

Are these missing textures?  I'm not sure/smart.

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
