### ISSUE TITLE
Obsidian Weathers fog sprites in interiors

### ISSUE THREAD

**Issue by gibsmegithub** [Lost-Outpost/septimus#590]
The mod author of obsidian describes this exact issue [here](https://www.nexusmods.com/skyrimspecialedition/mods/12125/?tab=posts).
> .:Known Issues:.
> 1. Interior fog during certain weathers.
> This is caused by having "bVolumetricLightingDisableInterior=0" in your Skyrim.ini under the [Display] header. This line causes the issue because the godrays aren't turned off when in interiors as they should be. To fix the issue, simply remove the line from your Skyrim.ini.

Simple enough fix, but for some reason deleting the line bVolumetricLightingDisableInterior from akyrim.ini or setting it to 1 (already set to 1 by default) doesn't fix the issue with Septimus. An easy way to reproduce it is to just enter "fw C8220" into the console while in an exterior cell and then enter an interior cell.

[Screenshot](https://media.discordapp.net/attachments/972219567654977606/1029105494096363651/SkyrimSE_2022-10-10_10-54-27.png?width=1062&height=597)

**Comment by Guitarninja2** [comment]
Should be fixed in theory.
