### ISSUE TITLE
Floating and overlapping meshes near Little Vivec

### ISSUE THREAD

**Issue by gibsmegithub** [Lost-Outpost/septimus#592]
Not sure if this is a conflict from Undeath (adds Little Vivec) and Undeath (adds the nearby Temple of Arkay) modifying the same cells or something else. But upon entering Little Vivec the first thing you'll notice is a boulder sticking through the bridge, then if you turn around you'll notice the Temple of Arkay is partially suspended above the ground, along with a number of plants and trees.

[Boulder](https://media.discordapp.net/attachments/972219567654977606/1029518141828644974/SkyrimSE_2022-10-11_14-06-23.png?width=996&height=560)
[Temple of Arkay](https://media.discordapp.net/attachments/972219567654977606/1029518142382280865/SkyrimSE_2022-10-11_14-06-37.png?width=996&height=560)
[Floating plants](https://media.discordapp.net/attachments/972219567654977606/1029518142831071303/SkyrimSE_2022-10-11_14-07-34.png?width=996&height=560)

**Comment by gibsmegithub** [comment]
Update after updating to latest 4.0.0 beta2- Boulder is gone, [however Temple of Arkay is growing increasingly sus](https://media.discordapp.net/attachments/972219567654977606/1029534431658131556/SkyrimSE_2022-10-11_15-16-31.png?width=996&height=560)

**Comment by Guitarninja2** [comment]
Fixed in latest version
