### ISSUE TITLE
Floating books/missing benches at Winterhold, Hall of Attainment

### ISSUE THREAD

**Issue by gibsmegithub** [Lost-Outpost/septimus#593]
Picture and title say it all. Also can't interact with the skills books for some reason.
![SkyrimSE 2022-10-11 15-20-48](https://user-images.githubusercontent.com/115591518/195216313-e9331c0c-8acc-4b4c-b25a-f00c08d5c453.png)

**Comment by Guitarninja2** [comment]
Fixed in 4.0.2
