### ISSUE TITLE
Crabber's Shanty - Missing Water and Floating Objects

### ISSUE THREAD

**Issue by Aphiberg** [Lost-Outpost/septimus#596]
![image](https://user-images.githubusercontent.com/95704963/195230273-acee474e-d993-42e4-bb70-aaa475057197.png)
![image](https://user-images.githubusercontent.com/95704963/195230294-2aa129d0-28f6-4e96-869d-d32cb1aafb97.png)

Console states that this area is being changed by Ryn's Crabber's Shanty. Images should show issue, notice floating cheese and book, as well as no water in dip where it is expected.

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
