### ISSUE TITLE
Keyboard Shortcuts Fix mod does not work

### ISSUE THREAD

**Issue by Durgenage** [Lost-Outpost/septimus#599]
We need  [xSHADOWMANx's DLL Loader](https://www.nexusmods.com/skyrimspecialedition/mods/3619) for this mod to work properly, since it's not updated for the AE versions of SKSE

**Comment by gibsmegithub** [comment]
Last time I tried any DLL loader on .353 or newer it completely broke my skyrim install and even removing it wouldn't fix it, would not recommend

**Comment by Durgenage** [comment]
Maybe you could elaborate a bit? The mod doesn't work and this is how you make it work. The alternative is to take the mod out completely.

**Comment by gibsmegithub** [comment]
I had the exact error [this guy had here](https://discord.com/channels/476382979501981696/972219566212145152/1029858696232177796) where I installed that and/or the other DLL loader out there. Removing the DLL loader just resulted in a different error. Ultimately I couldn't even launch Skyrim again with or without any mods until I nuked and reinstalled everything.
