### ISSUE TITLE
Enhanced Lights and FX - Border disputes and invasions (A.K.A, it's overwriting interior cells and doing funky things)

### ISSUE THREAD

**Issue by Aphiberg** [Lost-Outpost/septimus#601]
It would appear that one of the main culprits for a lot of the artifacting and anomalies encountered in Septimus is the Enhanced Lights and FX mods. This naughty mod attempts to fight for superiority, taking the other mods by surprise and getting a foothold where it shouldn't.

![image](https://user-images.githubusercontent.com/95704963/195380710-4ede39e8-e4d2-408e-a6fc-5938d162641d.png)
![image](https://user-images.githubusercontent.com/95704963/195380751-148ecdd7-1c46-43c8-be95-a41b676ff1fe.png)
![image](https://user-images.githubusercontent.com/95704963/195380785-aa619d1c-5a6f-4a15-8b43-1cba28c8f3dc.png)

Fort Dawnguard in this example fights valiantly, alas ELFX is persistent. Rumours have it that many other locations have had issues ranging from minor border disputes (I believe the College of Winterholds shrunk Wells), to full on invasion (Fort Dawnguard is the most severe one I have encountered... so far.)

It remains to be seen whether the great and powerful GuitarNinja will be able to mediate between these mods and create a peace treaty, or if we will need to support the other mods and eliminate ELFX.

**Comment by Guitarninja2** [comment]
Fixed in 4.0.1
