### ISSUE TITLE
Blackthorn Half Buried

### ISSUE THREAD

**Issue by silverymarie** [Lost-Outpost/septimus#602]
The Blackthorn buildable settlement has some weird land issues; when you get there it seems to be buried under a hill, and going behind the trader reveals big holes in the land. 

![enb2022_10_12_13_15_48](https://user-images.githubusercontent.com/102628346/195440475-6ade5b08-75bc-4b8d-8b1b-62d22b0009a3.jpg)
![SkyrimSE 2022-10-12 13-15-55](https://user-images.githubusercontent.com/102628346/195440537-1d9d98f9-3404-49ee-8615-0d5def4368ac.png)
![SkyrimSE 2022-10-12 13-16-02](https://user-images.githubusercontent.com/102628346/195440610-de8b23e8-0b87-4981-938b-7a198f4cff30.png)

**Comment by silverymarie** [comment]
Here's a couple more pictures from a better angle
![SkyrimSE 2022-10-12 13-33-39](https://user-images.githubusercontent.com/102628346/195443376-85abbc26-8ddc-4908-a0c0-aa73a3c5c990.png)
![SkyrimSE 2022-10-12 13-33-53](https://user-images.githubusercontent.com/102628346/195443388-6fd67c39-17b0-4dd5-b76f-57ecb9826f07.png)

**Comment by Guitarninja2** [comment]
Fixed in 4.0.1
