### ISSUE TITLE
Landscape/flora misalignment near Temple of Arkay

### ISSUE THREAD

**Issue by gibsmegithub** [Lost-Outpost/septimus#604]
[Issue #592](https://github.com/Lost-Outpost/septimus/issues/592) still present in 4.0.1 with new save. Facing east from west side of temple:
![SkyrimSE 2022-10-12 16-45-18](https://user-images.githubusercontent.com/115591518/195473581-9ad214e7-7166-49c1-a645-5c2d95238697.png)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
