### ISSUE TITLE
Cant progress past "Reach Alduin's portal to Sovngarde" in The World-Eater's Eyrie

### ISSUE THREAD

**Issue by trihard711** [Lost-Outpost/septimus#605]
I am able to do the main quest up until this point but when ever I get on the dragons back to ride to Skuldafn, if black screens. The only way I could get past it is threw console commands. If you try setting the quest stage to 50 (Reach Alduin's portal to Sovngarde) you freeze at the entrance of Skuldafn and cant move.

**Comment by Guitarninja2** [comment]
Can you upload your save file here? Also is this Septimus 3 or 4?

**Comment by Drust117** [comment]
From seeing other modlists I think this might be an issue with the Precision mod, a similar issue may occur with Touching the Sky with the frozen falmer not working/ clipping into the sky

**Comment by trihard711** [comment]
[Autosave1_8E4ECC13_0_53757373792062616B61_MidwoodIsleLastendellKingsQueensBasement_001756_20221013185826_19_1.zip](https://github.com/Lost-Outpost/septimus/files/9779858/Autosave1_8E4ECC13_0_53757373792062616B61_MidwoodIsleLastendellKingsQueensBasement_001756_20221013185826_19_1.zip)

Just a heads up, I do have to additional mods, one that adds another perk point after 5 levels and one that adds a perk point once a skill hits 50-75-100
