### ISSUE TITLE
Landscape issue, north side of Falkreath

### ISSUE THREAD

**Issue by icydawgfish** [Lost-Outpost/septimus#609]
![SkyrimSE 2022-10-14 19-26-11](https://user-images.githubusercontent.com/104177910/195960667-f4998a1d-d906-4722-919e-62b57c019add.png)
![SkyrimSE 2022-10-14 19-25-31](https://user-images.githubusercontent.com/104177910/195960669-14fc79d6-0cbd-4fbd-806d-f51fb5c05672.png)

You can walk through it, and inside is fine, but something is going on with the ground here

**Comment by icydawgfish** [comment]
![SkyrimSE 2022-10-14 19-29-57](https://user-images.githubusercontent.com/104177910/195960736-d77f318e-5a35-48d4-8bbc-a0eb968c1513.png)

**Comment by icydawgfish** [comment]
Just outside Reinhardts house

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
