### ISSUE TITLE
Anise's Cabin - walls disappear, general jank

### ISSUE THREAD

**Issue by icydawgfish** [Lost-Outpost/septimus#611]
When standing inside Anise's cabin, in some places, segments of the walls and furniture disappears, you can see straight through

**Comment by icydawgfish** [comment]
![enb2022_10_14_21_51_48](https://user-images.githubusercontent.com/104177910/195965716-4cf1b8a9-a7e5-401a-9e25-6dfa4b4dd3f4.jpeg)
![enb2022_10_14_21_51_53](https://user-images.githubusercontent.com/104177910/195965717-3438ffbc-eb8c-4f1c-990a-012611250167.jpeg)
![enb2022_10_14_21_51_57](https://user-images.githubusercontent.com/104177910/195965718-d8b09c48-5025-4cd6-9711-197a2ab874f6.jpeg)
![enb2022_10_14_21_51_43](https://user-images.githubusercontent.com/104177910/195965721-fb769a43-a80a-4075-8f08-71704bf3d854.jpeg)

**Comment by Liareth** [comment]
I've noticed this on the stairs down into the Midden in the College of Winterhold too.

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
