### ISSUE TITLE
floating trees by wayshrine between Anise's cabin and riverwood

### ISSUE THREAD

**Issue by icydawgfish** [Lost-Outpost/septimus#612]
![enb2022_10_14_21_57_49](https://user-images.githubusercontent.com/104177910/195965960-d12009ff-398e-4142-9a40-f60f7ba90b98.jpeg)
![enb2022_10_14_21_57_57](https://user-images.githubusercontent.com/104177910/195965962-b65d9afc-ed4e-4422-8824-1098af08d2f0.jpeg)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
