### ISSUE TITLE
Temple of Mara is a bit messed up on the inside

### ISSUE THREAD

**Issue by Foamimi** [Lost-Outpost/septimus#613]
Hello !! I popped into the Temple of Mara to take NPC pictures when I noticed the place was a bit screwed up. Floating banners, floating food, hearthfire stove along the side in the main room, etc. Seemed like a mini battle between JK's Temple of Mara and Houses-Shops-Inns Basic.

[https://i.imgur.com/4E1QyGu.png](https://i.imgur.com/4E1QyGu.png)
[https://i.imgur.com/e308LRu.png](https://i.imgur.com/e308LRu.png)
[https://i.imgur.com/0Ip0X56.png](https://i.imgur.com/0Ip0X56.png)
[https://i.imgur.com/jG69RL7.png](https://i.imgur.com/jG69RL7.png)

Any help/fix would be immensely appreciated! <3

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
