### ISSUE TITLE
Floating rocks at the Giant's Camp near Whiterun

### ISSUE THREAD

**Issue by IIBendyII** [Lost-Outpost/septimus#616]
Said rocks seems to belong to "Ryn's Bleackwind Basin.esp"
![enb2022_10_16_16_52_38](https://user-images.githubusercontent.com/115938680/196043259-97192e48-a1d3-4d66-b437-45ea0d4f4c65.jpeg)
![enb2022_10_16_16_52_51](https://user-images.githubusercontent.com/115938680/196043262-bc2db69d-b7cb-44c2-a0d0-155dacff7144.jpeg)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
