### ISSUE TITLE
Floating crops and fences at the farm outside Riften

### ISSUE THREAD

**Issue by IIBendyII** [Lost-Outpost/septimus#617]
The floating objects belong to "Ryn's Farms.esp"
![SkyrimSE 2022-10-16 16-56-03](https://user-images.githubusercontent.com/115938680/196043485-6250b849-e00d-48c8-acbb-12b48af7cca1.jpeg)
![SkyrimSE 2022-10-16 16-56-22](https://user-images.githubusercontent.com/115938680/196043491-0d4a4ef6-cda9-411c-a249-ea0b287d5b3a.jpeg)
There is also grass growing inside the wooden walkway nearby. Said walkway also comes from Ryn's Farms
![SkyrimSE 2022-10-16 16-56-37](https://user-images.githubusercontent.com/115938680/196043500-e1b62caa-4f91-481d-a516-cb595fa61cf4.jpeg)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
