### ISSUE TITLE
Dwarven arrow quiver has missing textures

### ISSUE THREAD

**Issue by Igruola** [Lost-Outpost/septimus#618]
Bought a dwarven arrow, has missing textures.
![20221017101751_1](https://user-images.githubusercontent.com/62115650/196202734-c6d79c56-6aab-4d7d-b71f-343f280acb7b.jpg)
Base last changed by Weapons and Armor Overhaul
![image](https://user-images.githubusercontent.com/62115650/196202906-b776eed4-97ca-44b9-86c9-65c8d6b0fc8d.png)
This install of Septimus is unchanged from base, no optional things enabled or widescreen fixes.

**Comment by Guitarninja2** [comment]
Fixed in 4.0.2
