### ISSUE TITLE
Snow-Shod Manor wall raised up showing out-of-bounds

### ISSUE THREAD

**Issue by Igruola** [Lost-Outpost/septimus#625]
here's the wall
![image](https://user-images.githubusercontent.com/62115650/197335976-e1c69383-16d6-4adf-aa4e-ab7c219ba6e4.png)
Console images with wall selected
![image](https://user-images.githubusercontent.com/62115650/197336018-01fc7175-9b7e-46c4-b439-af0c651221e2.png)
![image](https://user-images.githubusercontent.com/62115650/197336023-a2911740-54ad-4b85-8740-4715fc9226e6.png)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
