### ISSUE TITLE
Missing water at Crabber's Shanty

### ISSUE THREAD

**Issue by Goldiees** [Lost-Outpost/septimus#628]
![Missing water](https://user-images.githubusercontent.com/116525403/197422098-a3bcc84d-45a8-4969-bff6-2a6295b1ce66.png)
![unknown](https://user-images.githubusercontent.com/116525403/197422328-f6e0cc8d-0129-488f-8584-44db6d45aa0b.png)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
