### ISSUE TITLE
Werewolf Alternate Start - Spawn Inside a Rock

### ISSUE THREAD

**Issue by Foamimi** [Lost-Outpost/septimus#631]
Hello again! I just noticed when you do the alternate start - werewolf choice, you spawn inside of a rock added by DynDOLOD. Here are a few images to show what I mean:

[https://i.imgur.com/dAcgCWh.png](https://i.imgur.com/dAcgCWh.png)
[https://i.imgur.com/L1AHEG9.png](https://i.imgur.com/L1AHEG9.png)
[https://i.imgur.com/Rgqjux4.png](https://i.imgur.com/Rgqjux4.png)
[https://i.imgur.com/zgU8umq.png](https://i.imgur.com/zgU8umq.png)
[https://i.imgur.com/PNEP7wz.png](https://i.imgur.com/PNEP7wz.png)

I tried disabling the rock in-game but it didn't actually disappear. It's not a huge problem by any means since you can just walk through the rock, you just can't go back to that starting point and the NPCs clip a teeny bit, but I just thought I'd report it anyway since it was something I noticed. Sorry to bother. >.<

**Comment by Guitarninja2** [comment]
LOL
