### ISSUE TITLE
error on loading a game, using Septimus 4

### ISSUE THREAD

**Issue by cfrederi** [Lost-Outpost/septimus#632]
Well - Problem has shown up again. And I can reproduce it - happens every time I run the game... :(
I'm no longer a happy woman, but I'll start a new game, and hope that this error message is the only issue..
Cheers, Charlotte

UPDATE UPDATE: I ran the troubleshooter for Modorganizer - and Windows  altered UAC, so that MO2 runs as administrator - that fixed the problem - error not shown...

I'm a happy woman! - I'll go and kill some Silver Hands now....

Cheers, Charlotte

Hi.

Yesterday - after playing for a few days without problems with this modlist - I suddenly got an error on loading a save game

![Billede1](https://user-images.githubusercontent.com/26874158/198112651-2930e415-0029-48dc-8c38-7f3ca0934a72.png)

The game was installed  in C:/SteamLibrary,  and NOT in the default steamfolder. I installed the modlist using the location: C:/Wabbajack/SkyrimAE_Septimus - so that the same drive was used for the game and the modlist.
I also removed the existing copy of the game, and made a clean install, as  explained in the README. document.

I  have not installed additional mods.

In steam I have disabled automatic update of the game.

I'm running Windows11 Home edition.

And as noted above, the game ran without problems for a few days...

I  have tried tried running the jabbawack install process again, and I have tried to make a clean install of SkyrimAE in D:/SteamLibrary as well as a clean install of the Septimus4 list in D:/Wabbajack/Skyrim_AE.  But I get the same error

The root of the trace-stack says: PermissionError: [Errno 13] Permission denied: 'D:\\wabbajack\\Skyrim_AE\\GameRoot\\bink2w64.dll'
So it must be some permission error (I believe) . The game does start afterwards, but I  feel uncomfortable starting up a game in this way, as I have no idea if something is broken

I hope you can help! I really like this list, the graphics are great!

Cheers, Charlotte

**Comment by Guitarninja2** [comment]
I can't diagnose this through github, please use the discord.

**Comment by HugoCornay** [comment]
What did you do to fix the error?
