### ISSUE TITLE
Can't get screen to fit 21:9 monitor

### ISSUE THREAD

**Issue by WheresTheCashola** [Lost-Outpost/septimus#633]
Hi there,

I am trying to get Septimus 4.0 to fit my 3440 x 1440 monitor but when I start Skyrim the game screen is zoomed in quite a lot so I can't see all the options

I have selected all of the widescreen support options and changed their Load priority on the left hand screen of the Mod organiser but I can't see them appear in the right side (Plug-ins)

I also attempted to manually change the screen resolution in the SSE Display tweak mods section on account of some advice from Reddit but the screen still remains the same

Hopefully the below attachments work as I have never used Github before
![20221026_231317 1](https://user-images.githubusercontent.com/116769976/198157868-b4cab704-b18f-4487-bd0a-bc310401a34e.jpg)

![20221026_231556 1](https://user-images.githubusercontent.com/116769976/198157695-a4dea22c-d0ce-4f47-9c9e-1c90ac4f439b.jpg)
![20221026_231330 1](https://user-images.githubusercontent.com/116769976/198157795-ebf478f5-4e4c-4a58-9a7b-0b470e86fac4.jpg)

**Comment by Guitarninja2** [comment]
Come to the discord for support with this. I can't troubleshoot here. It's not a modlist issue.
