### ISSUE TITLE
Overlapping furniture in High Hrothgar

### ISSUE THREAD

**Issue by IIBendyII** [Lost-Outpost/septimus#634]
Certain furniture overlaps with eachother in High Hrothgar. These overlapping pieces belong to "JK's High Hrothgar.esp" and "HousesShopsInns_Basic.esp". They also provide two separate enchanting tables.

![enb2022_10_27_16_47_37](https://user-images.githubusercontent.com/115938680/198327641-2e000740-3e1d-499c-8267-81f7eabba8aa.jpeg)
![enb2022_10_27_16_50_19](https://user-images.githubusercontent.com/115938680/198327782-c482838f-92ea-415e-afdb-fb5aafc54f60.jpeg)

**Comment by Guitarninja2** [comment]
Fixed in 4.1.0
