### ISSUE TITLE
Balance: Master Transmute Spell

### ISSUE THREAD

**Issue by Aphiberg** [Lost-Outpost/septimus#641]
The Bittercup CC quest adds a new spell called "Master Transmute", this spell, compared to Mysticism's version, allows a caster to turn one iron or one silver ore directly into one gold ore. The Mysticism version requires 2 iron for 1 silver, and 2 silver for 1 gold ore. 

This is not in itself a problem, as this spell is a rare reward for a specific path taken in the Bittercup quest, and I feel an appropriate upgrade. The real problem is in the spells cost. In my game when I added in out of curiosity, I got a spell cost of around 56, compared to Mysticisms which was about 135. 

I think a spell such as this should be made into an Expert or Master level spell, and its spell cost increased accordingly in order to account for the significant boost to transmutation efficiency. Alternatively, you could perhaps tweak the spell to require 2 iron ore for 1 gold, and 1 silver to 1 gold.

**Comment by Guitarninja2** [comment]
Yeah these seem reasonable. I'll look at doing this in an upcoming update if no one has already done it.
