### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by TigerMonkeyOne** [Lost-Outpost/septimus#648]
[Wabbajack.current.log](https://github.com/Lost-Outpost/septimus/files/9977793/Wabbajack.current.log)

I tried about 6 times to reinstall this but it keeps failing.  Any help?

**Comment by JayTurtle** [comment]
Same here. Issues downloading an archive, been happening all week.

Error log attached.

[Wabbajack.current.log](https://github.com/Lost-Outpost/septimus/files/9984521/Wabbajack.current.log)

**Comment by nopelt** [comment]
Do you guys have https://store.steampowered.com/agecheck/app/1746860/
if not thats why 
if u have then run skyrim through steam and download everything from creation club

**Comment by JayTurtle** [comment]
No just the Special Edition. Is there a workaround for this?

**Comment by JayTurtle** [comment]
Confirmed, this was the issue. Bought AE and downloaded all creations, Mod List now downloads properly.

**Comment by TigerMonkeyOne** [comment]
Forgive me.  I dont understand the fix.  Can you walk me through it?

**Comment by JayTurtle** [comment]
@TigerMonkeyOne Basically, the Mod List will not onstall correctly unless you have the Skyrim Anniversary Edition DLC installed. The installation guide does say this but I didn't read it thoroughly.

So, what you have to do is buy the Anniversary Edition DLC for Skyrim (£8.99 on CD Keys, roughly the same in dollars I think), then open the game, go to the Bethesda Creation Club in the main menu, then go to the "Purchased" tab.

There is an option to "Download All" but the game kept freezing for me when I did this so I recommend choosing each creation individually and installing it. Some take seconds to download, some can take a couple minutes depending on your download speed.

After you've downloaded everything, go back to the Mod List and run the install again. It will download any missing files which shouldn't take too long, then it will install the mod list properly.

**Comment by TigerMonkeyOne** [comment]
Thanks.  I will try that.
