### ISSUE TITLE
I Downloaded Septimus Today, Having Trouble Launching

### ISSUE THREAD

**Issue by icelandicnord** [Lost-Outpost/septimus#655]
I downloaded the modlist today after a clean reinstall of Skyrim. I open Mod Organizer and click on "Run" - however, I get a message "Application must run to completion because its output is required", so I click on "unlock" but then this appears:

![Screenshot (291)](https://user-images.githubusercontent.com/75916167/202575910-0d7a7f55-e04c-40e4-967a-5850937b9439.png)

I've thoroughly read the installation and can't find a solution, however if I've missed it, I'd appreciate it being pointed out.
Any help would be greatly appreciated!

**Comment by HugoCornay** [comment]
Same problem here

**Comment by Albinoso98** [comment]
Same problem

![image](https://user-images.githubusercontent.com/49130371/202853392-2293b8cb-169b-4f10-a71a-2c8726f484fb.png)

![image](https://user-images.githubusercontent.com/49130371/202853407-85289bad-78af-4dcc-8cb0-cfe103c03fe7.png)

**Comment by screwyprof** [comment]
@icelandicnord  Try to restart Mod Organizer
