### ISSUE TITLE
Seem to be missing SkyrimSe

### ISSUE THREAD

**Issue by HugoCornay** [Lost-Outpost/septimus#656]
Downloaded the mod today and I get an error that I am missing Skyrim Script Extender... not sure what to do or where to add skse

![Capture](https://user-images.githubusercontent.com/51824896/202822569-8855ef96-935e-4b3b-ac7d-b206697dc65f.PNG)

**Comment by HugoCornay** [comment]
![image](https://user-images.githubusercontent.com/51824896/202822701-90fbbc14-1950-4dd3-b0e4-02936f814682.png)

**Comment by screwyprof** [comment]
@HugoCornay @HugoCornay Just restart Mod Organizer

**Comment by HugoCornay** [comment]
No change..

**Comment by nhopkins85** [comment]
Same issue. Followed all the readme instructions to the letter (I think) and had no problem with any part of the process until I try to start the game.

Sometimes I get this window...
![Screenshot 2022-11-26 135034](https://user-images.githubusercontent.com/119114341/204090073-6c237b55-987f-41ff-bd17-64773a013235.png)
Sometimes I don't.

But I always get these windows:
![Screenshot 2022-11-26 120037](https://user-images.githubusercontent.com/119114341/204090118-965e03ed-08ab-4c7e-a781-1634a609a3b6.png)
![Screenshot 2022-11-26 113419](https://user-images.githubusercontent.com/119114341/204090126-459a60d4-8a29-4492-b286-51b1a3e65c25.png)

When I click "Unlock", it seems like Skyrim is loading (see below)...
![Screenshot 2022-11-26 134129](https://user-images.githubusercontent.com/119114341/204090217-deb04e28-a21d-47eb-a5d5-7a8da1140f4c.png)

...but when I click on the window it's zoomed in to the top left corner of the screen and I can't navigate anything and have to force quick via the task manager.

Sorry if there's a really easy fix. I'm really new to this :)

**Comment by HugoCornay** [comment]
What worked for me is two things, first I had to either add fake ram but using my SSD as a backup whenever it gets saturated. And also very important when the game opens and there's the message needed to unlock SkyrimSE don't click anything just click play once and let it run and works fine now

**Comment by screwyprof** [comment]
I’ve noticed that you installed Septimus inside the wabajack folder. Try installing it in to the root, e.g c:\Septimus or d:\septimus
