### ISSUE TITLE
More Duplicates

### ISSUE THREAD

**Issue by StarfleetCommand** [Lost-Outpost/septimus#676]
https://imgur.com/a/xq6CiSK

**Comment by Roofcrawler** [comment]
I'm getting duplicate books too. 
Probable cause is that Book Covers Skyrim and Book Covers Skyrim Lost Library are in the modlist as well as Legacy of the Dragonborn. 
According to LOTD Full Guide Compatibility page: https://www.nexusmods.com/skyrimspecialedition/articles/1494

Incorporated Mods:
This list of mods are incorporated or assets were contributed to LOTD and SHOULD NOT be installed as their content has already been included with Legacy. Adding these mods in addition to Legacy may cause conflicts and will void any support we can offer.

Big Leather Backpack (by hideto84 with edits to recipe)
**Book Covers Skyrim
Book Covers Skyrim Lost Library**
Edhelsereg's Lord's Mail
Engelman's Rest dungeon
Gemstone Collector (gemstones only version with edits for compatibility. See update notes)
Insanity's Chrysamere
keizaalfeyn's Dawnfang
Luxurious Pickaxes
Much Ado About Snow Elves
MyBad's Shadow of the Underking
Nimezis Daedric Crescent
Nordic Wanderer Equipment
Ogmund's Tomb dungeon (as Dragon's Fall)
Painkiller97's Hrothmund's axe
PrivateEye's BiPolar Blade
PrivateEye's Helm of Oreyn Bearclaw
PrivateEye's Helm of Tohan
PrivateEye's rings of old
PrivateEye's sixth house bellhammer
Ronnie Magnum's Legendary Rings V2.0
Saeralith's White Phial Replacer
Thane Weapons Reborn
Theycallmecheese's Ancient Shrouded Armor replacer
Trainwiz's Visage of Mzund redone
Unique Booze Bottles HD
Unique Uniques
Windcaller Pass dungeon
Wulfharth's Fang of Haynekhtnamet
Ysgramor's Armor- Sea shells collection
