### ISSUE TITLE
a collection of issues with Septimus 1.0.3

### ISSUE THREAD

**Issue by thehermittt** [Lost-Outpost/septimus#689]
so i have a few issues, here's a copy of my discord post:

hello, the LOD for the dragonborn museum in solitude (when looking from the solitude docks for example) is missing for me, only parts of it appear floating in mid-air 
it was missing in septimus 4.3 for me too, so i had to re-do all the dyndolod stuff to make it show up properly, and now i installed latest septimus version and its missing again...
![ScreenShot1](https://user-images.githubusercontent.com/122132848/211122609-cce11fb7-c84a-4fdf-a568-730de1a95ae6.png)
guess i will have to re-do the dyndolod again? but i cant be the only one with that specific problem?

i also have other problems: east empire trading company woman does nothing when i select the option to trade, the dialog window just closes...
![ScreenShot2](https://user-images.githubusercontent.com/122132848/211122631-9308eb84-81f5-4636-9b54-b058e686de18.png)

and there is no ship from "wares of tamriel" in dawnstar although the mod is installed?
![ScreenShot0](https://user-images.githubusercontent.com/122132848/211122648-589287f6-a6be-486d-8d8f-f05cce73a29a.png)

and the last problem is that CC armors such as iron plate or steel soldier seem to be missing from the crafting menus and from the leveled lists, and there is no quest notes for them in the usual places. i understand that tamrielic distribution and crimson trail should remove the quest requirements for the armors and u would only need smithing perks to make them, but even the iron one does not show. 
![ScreenShot3](https://user-images.githubusercontent.com/122132848/211122768-83dcab96-aeb7-4e35-9778-92d097468a55.png)

i cleared like 7 bandit camps and did not see a single piece of iron plate armor there too...

thanks in advance! and thanks for the awesome modlist

**Comment by Guitarninja2** [comment]
Leaving this here as a checklist for things to look into

- [ ] Wares of Tamriel Boat - This is intended. It's moved to the wyrmstooth island and will show up after a certain point in that quest
- [ ] CC Iron Armor - Looks like you need to complete The Only Cure quest as per Tamrielic Distribution. They can be found in Bruma as well though
- [ ] LOTD DynDolod - I need to look into this. I'm not entirely sure why it's still hidden. I just re-did the LODs
- [ ] Docks Shopkeeper - This is apparently a known issue with the Gladys mod
