### ISSUE TITLE
Discord Rich Presence Still Says "Dragonborn"

### ISSUE THREAD

**Issue by m0thde** [Lost-Outpost/septimus#693]
When you click on someone's avatar/icon in Discord that's playing Septimus the box at the bottom says "Dragonborn - Nexus Mods" and links to the Dragonborn Nexus page.

![image](https://user-images.githubusercontent.com/121763260/229391763-90d8976e-be3f-4408-a5b0-3cdbf4e7958f.png)

**Comment by Guitarninja2** [comment]
Should be fixed now
